### ISSUE TITLE
ppx_expect v0.14.1 not working with dune or merlin

### ISSUE THREAD

**Issue by bikallem** [janestreet/ppx_expect#26] opened 2020-12-03 10:05 UTC
Here is the issue of ppx_expect not generating correct merlin details. Does this issue belong here? https://github.com/ocaml/ocaml-lsp/issues/310

**Comment by jeremiedimino** [comment] 2020-12-03 16:41
Could you give a reproduction case?

**Comment by bikallem** [comment] 2020-12-04 10:02
Sure, here is a simple dune project,
```
$ cat dune 
(library
 (inline_tests)
 (name ppx_expect1)
 (preprocess
  (pps ppx_inline_test ppx_expect)))

$ cat hello.ml
let a () = 
  print_string "hello"

let%test "" = (1 = 1)

let%expect_test _ = 
  a ();
  [%expect {||}]
```
The project builds okay, however, merline complains with the following in my vim editor,
```
ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)
```
Here is the generated `.merlin` file
```
EXCLUDE_QUERY_DIR
B /home/bikal/.opam/4.11.1/lib/base
B /home/bikal/.opam/4.11.1/lib/base/base_internalhash_types
B /home/bikal/.opam/4.11.1/lib/base/caml
B /home/bikal/.opam/4.11.1/lib/base/shadow_stdlib
B /home/bikal/.opam/4.11.1/lib/jane-street-headers
B /home/bikal/.opam/4.11.1/lib/ppx_compare/runtime-lib
B /home/bikal/.opam/4.11.1/lib/ppx_enumerate/runtime-lib
B /home/bikal/.opam/4.11.1/lib/ppx_expect/collector
B /home/bikal/.opam/4.11.1/lib/ppx_expect/common
B /home/bikal/.opam/4.11.1/lib/ppx_expect/config
B /home/bikal/.opam/4.11.1/lib/ppx_expect/config_types
B /home/bikal/.opam/4.11.1/lib/ppx_hash/runtime-lib
B /home/bikal/.opam/4.11.1/lib/ppx_here/runtime-lib
B /home/bikal/.opam/4.11.1/lib/ppx_inline_test/config
B /home/bikal/.opam/4.11.1/lib/ppx_inline_test/runtime-lib
B /home/bikal/.opam/4.11.1/lib/ppx_sexp_conv/runtime-lib
B /home/bikal/.opam/4.11.1/lib/sexplib0
B /home/bikal/.opam/4.11.1/lib/time_now
B _build/default/.ppx_expect1.objs/byte
S /home/bikal/.opam/4.11.1/lib/base
S /home/bikal/.opam/4.11.1/lib/base/base_internalhash_types
S /home/bikal/.opam/4.11.1/lib/base/caml
S /home/bikal/.opam/4.11.1/lib/base/shadow_stdlib
S /home/bikal/.opam/4.11.1/lib/jane-street-headers
S /home/bikal/.opam/4.11.1/lib/ppx_compare/runtime-lib
S /home/bikal/.opam/4.11.1/lib/ppx_enumerate/runtime-lib
S /home/bikal/.opam/4.11.1/lib/ppx_expect/collector
S /home/bikal/.opam/4.11.1/lib/ppx_expect/common
S /home/bikal/.opam/4.11.1/lib/ppx_expect/config
S /home/bikal/.opam/4.11.1/lib/ppx_expect/config_types
S /home/bikal/.opam/4.11.1/lib/ppx_hash/runtime-lib
S /home/bikal/.opam/4.11.1/lib/ppx_here/runtime-lib
S /home/bikal/.opam/4.11.1/lib/ppx_inline_test/config
S /home/bikal/.opam/4.11.1/lib/ppx_inline_test/runtime-lib
S /home/bikal/.opam/4.11.1/lib/ppx_sexp_conv/runtime-lib
S /home/bikal/.opam/4.11.1/lib/sexplib0
S /home/bikal/.opam/4.11.1/lib/time_now
S .
FLG -ppx '/home/bikal/github/ppx_expect1/_build/default/.ppx/423b3c0918a91461d11b9cd1259aca91/ppx.exe --as-ppx --cookie '\''inline_tests="enabled"'\'' --cookie '\''library-name="ppx_expect1"'\'''
FLG -open Ppx_expect1 -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

**Comment by bikallem** [comment] 2020-12-04 10:08
Here is the `ppx_expect` error,
```
ppx_expect: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)
```

**Comment by jeremiedimino** [comment] 2020-12-07 10:03
By looking at the merlin file, it seems that the relevant flags are passed correctly:

```
--cookie '\''inline_tests="enabled"'\'' --cookie '\''library-name="ppx_expect1"'\'''
```

So not sure what's going on. You can add some printf in `ppx_inline_test` to see if the information is indeed passed through. A good place to start is `libname/ppx_inline_test_libname.ml` in the source code of `ppx_inline_test`.

**Comment by bentrevor** [comment] 2020-12-13 21:52
I looked into this a little bit but I'm still not sure what the issue is. It seems like it might be something with merlin, but I'm having trouble confirming it.

I was seeing the same behavior as bikallem: both `ppx_inline_test` and `ppx_expect` were showing the `-inline-test-lib` error in my editor, but I was able to execute `dune runtest` without any problems from a terminal. I added print statements to `ppx_inline_test` to confirm that `libname` is being set based on the flag that is passed in, so `can_use_test_extensions` is true as expected. However, `libname` was still None when I checked it from merlin by logging it to the `extension is disabled` message.

It seems like it boils down to these lines of code: https://github.com/janestreet/ppx_inline_test/blob/master/libname/ppx_inline_test_libname.ml#L12-L17 Running it from the terminal is matching `Some lib`, but merlin is matching `None`. I have no idea how Driver.Cookies works and I don't have any more time to look at this today, but if you have any other tips on what to do, I can try again later this week.

(I can also open an issue for this in the ppx_inline_test repo if you'd prefer to track it there)

**Comment by jeremiedimino** [comment] 2021-01-11 10:43
We can continue the discussion here.

One thing you can try is printing `Sys.argv`, to see what exactly is passed to the ppx driver program.

It is also worth trying with the master of https://github.com/ocaml-ppx/ppxlib. The code handling `-as-ppx` (which is used by merlin) used to be spaghetti code and we [recently cleaned it up](https://github.com/ocaml-ppx/ppxlib/pull/197). So it might work better now.

**Comment by jeremiedimino** [comment] 2021-01-13 10:18
I think I found the issue. If it is what I think it is, then this regression was introduced with the switch to omp 2. I'll prepare a PR against ppxlib.

**Comment by jeremiedimino** [comment] 2021-01-13 10:32
It wasn't that. So no more progress on this.

**Comment by jeremiedimino** [comment] 2021-01-18 09:58
We had a look on the ppxlib side with @pitag-ha and she added a [test](https://github.com/ocaml-ppx/ppxlib/pull/208/files#diff-e35b7f4f3668e1c5ad9c9633f2bc37cab051e831080cf0f30675f7d1263cb8d0) that demonstrates that the issue is on the ppxlib side. This should be fixed in the next release of ppxlib.

**Comment by jeremiedimino** [comment] 2021-01-18 14:46
From our point of view, this is now fixed in the master of ppxlib. I'll close this ticket after the next release of ppxlib.

**Comment by jeremiedimino** [comment] 2021-01-25 09:54
the new version of ppxlib that has the fix has now been released: https://github.com/ocaml/opam-repository/pull/18019

**Closed by jeremiedimino** 2021-01-25 09:54 UTC
Labels: forwarded-to-js-devs
